from django.db import models
from django.utils import timezone

class Story(models.Model):
    """
    Represents a single creative generation, storing both the inputs
    and the final outputs of the AI pipeline.
    """
    # Input
    user_prompt = models.TextField(
        help_text="The initial prompt provided by the user."
    )

    # Chain 1 Outputs
    story_text = models.TextField(
        help_text="The generated story text."
    )
    character_description = models.TextField(
        help_text="The detailed character description generated by the AI."
    )
    background_description = models.TextField(
        help_text="The detailed background description generated by the AI."
    )
    art_style = models.CharField(
        max_length=255,
        help_text="The unifying art style for the scene."
    )

    # Chain 2 & 3 Outputs
    final_character_prompt = models.TextField(
        help_text="The final, optimized prompt for character image generation."
    )
    final_background_prompt = models.TextField(
        help_text="The final, optimized prompt for background image generation."
    )

    # Chain 4 Output
    combined_image_path = models.CharField(
        max_length=255,
        blank=True,
        help_text="The path to the final combined image in static files."
    )

    # Timestamp
    created_at = models.DateTimeField(
        default=timezone.now,
        help_text="The date and time the story was created."
    )

    def __str__(self):
        """String representation of the model."""
        return f"Story for '{self.user_prompt[:50]}...' created on {self.created_at.strftime('%Y-%m-%d')}"

